product1 = input("Enter product 1: ")
product2 = input("Enter product 2: ")
product3 = input("Enter product 3: ")
product4 = input("Enter product 4: ")
print("List:")
print("1. " + product1)
print("2. " + product2)
print("3. " + product3)
print("4. " + product4)
